from userlibs import testuserlib

def foo():
    testuserlib.printstr(1, 2)
    testuserlib.println(2, 3)

def math_test():
    print testuserlib.math_add(1, 2, 3)
    print testuserlib.math_add(100, -30)
    print testuserlib.math_add(-100, -30)
    print testuserlib.math_add(-100, 30)
    print testuserlib.math_power(2, 3)
    print testuserlib.math_power(2.5, 3.2)

def on_callback(msg):
  print msg

def callback_test():
  testuserlib.init_callback(on_callback)
  testuserlib.trigger_callback()
  testuserlib.trigger_callback()
  print 'success'

def fib(n):
    if n<2:
        return n
    return fib(n-1)+fib(n-2)

def fib_test():
    print fib(1)
    print fib(2)
    print fib(3)
    print fib(4)
    print fib(5)
    print fib(6)
    print fib(7)
    print fib(8)
    print fib(9)
    print fib(10)
    print fib(1)
    print fib(2)
    print fib(3)
    print fib(4)
    print fib(5)
    print fib(6)
    print fib(7)
    print fib(8)
    print fib(9)
    print fib(10)
    print fib(1)
    print fib(2)
    print fib(3)
    print fib(4)
    print fib(5)
    print fib(6)
    print fib(7)
    print fib(8)
    print fib(9)
    print fib(10)
    print fib(1)
    print fib(2)
    print fib(3)
    print fib(4)
    print fib(5)
    print fib(6)
    print fib(7)
    print fib(8)
    print fib(9)
    print fib(10)
    print fib(1)
    print fib(2)
    print fib(3)
    print fib(4)
    print fib(5)
    print fib(6)
    print fib(7)
    print fib(8)
    print fib(9)
    print fib(10)
    print fib(1)
    print fib(2)
    print fib(3)
    print fib(4)
    print fib(5)
    print fib(6)
    print fib(7)
    print fib(8)
    print fib(9)
    print fib(10)
    print fib(1)
    print fib(2)
    print fib(3)
    print fib(4)
    print fib(5)
    print fib(6)
    print fib(7)
    print fib(8)
    print fib(9)
    print fib(10)
    print fib(1)
    print fib(2)
    print fib(3)
    print fib(4)
    print fib(5)
    print fib(6)
    print fib(7)
    print fib(8)
    print fib(9)
    print fib(10)


def main():
    foo()
    math_test()
    print fib(10)
    print fib(15)
    callback_test()
    print fib(10)
    print fib(15)
