# DO NOT EDIT THIS FILE
# This file is autogenerated from userlibsgen.py

def digitalRead(*arg):
    pass

def digitalWrite(*arg):
    pass

def pinMode(*arg):
    pass

def analogRead(*arg):
    pass

def analogWrite(*arg):
    pass

def delay(*arg):
    pass

def delayMicroseconds(*arg):
    pass

def millis(*arg):
    pass

def micros(*arg):
    pass

def attachInterrupt(*arg):
    pass

def detachInterrupt(*arg):
    pass

