# DO NOT EDIT THIS FILE
# This file is autogenerated from userlibsgen.py

def begin(*arg):
    pass

def beginTransmission(*arg):
    pass

def endTransmission(*arg):
    pass

def write(*arg):
    pass

def available(*arg):
    pass

def read(*arg):
    pass

