# DO NOT EDIT THIS FILE
# This file is autogenerated from userlibsgen.py

def begin(*arg):
    pass

def setChannel(*arg):
    pass

def setAddressWidth(*arg):
    pass

def setPALevel(*arg):
    pass

def openReadingPipe(*arg):
    pass

def openWritingPipe(*arg):
    pass

def startListening(*arg):
    pass

def stopListening(*arg):
    pass

def write(*arg):
    pass

def available(*arg):
    pass

def read(*arg):
    pass

