# DO NOT EDIT THIS FILE
# This file is autogenerated from userlibsgen.py

def init(*arg):
    pass

def set_on_recv_callback(*arg):
    pass

def send(*arg):
    pass

def powerdown(*arg):
    pass

def powerup(*arg):
    pass

