# DO NOT EDIT THIS FILE
# This file is autogenerated from userlibsgen.py

def beginTransaction(*arg):
    pass

def begin(*arg):
    pass

def end(*arg):
    pass

def transfer(*arg):
    pass

def endTransaction(*arg):
    pass

